apiVersion: v1
kind: Service
metadata:
  name: nodejs
  labels:
    app: nodejs
spec:
  type: ClusterIP
  selector:
    app: nodejs
  ports:
    - protocol: TCP
      name: http
      port: 9092
      targetPort: 9092