version: '2'
services:
  kafka:
    image: bitnami/kafka:latest
    networks:
      - kafka-network
    ports:
      - 9092:9092
    environment:
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CFG_ZOOKEEPER_CONNECT:
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
  nodejs-kafka:
    build: .
    networks:
      - kafka-network
    environment:
      KAFKA_ADDR: kafka:9092
    depends_on:
      - kafka
  logstash:
    image: logstash:7.17.10
    networks:
      - kafka-network
    volumes:
      - ./logstash-kafka.conf:/usr/share/logstash/pipeline/logstash.conf
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTICSEARCH_HOST: elasticsearch
    depends_on:
      - kafka
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
    networks:
      - kafka-network
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      http.max_content_length: "1000mb"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

volumes:
  elasticsearch-data:
  
networks:
  kafka-network:
    driver: bridge
