apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: logstash
spec:
  type: ClusterIP
  selector:
    app: logstash
  ports:
    - protocol: TCP
      name: http
      port: 9200
      targetPort: 9200
